# Proyecto de Mineria de Datos #
## CodelCOVID-19##
### Analisis exploratorio de datos###

En este documento se realizara el analisis exploratorio de datos de dos tipos de dataset:
* Dataset de el valor de criptomoneda por fecha
* Dataset de cantidad de contagiados por dia de diferentes paises del mundo ordenados alfabeticamente

In [2]:
import pandas as pd
df= pd.read_excel("BTC.xlsx")
df.head()

           Date     Open     High     Low     Close      Volume     Market Cap
0  Jul 13, 2020  9277.20  9306.40  9224.29  9243.61  17519821266  170379677119
1  Jul 12, 2020  9241.06  9319.42  9197.45  9276.50  14452361907  170977422928
2  Jul 11, 2020  9277.51  9293.53  9199.49  9240.35  13249910444  170302234778
3  Jul 10, 2020  9273.36  9287.47  9118.00  9278.81  16860035605  171001933827
4  Jul 09, 2020  9427.99  9431.38  9235.00  9277.97  18000702524  170977231638

In [3]:
df2=pd.read_excel("ETH.xlsx")
df2.head()

           Date    Open    High    Low    Close     Volume    Market Cap
0  Jul 14, 2020  239.98  242.00  237.80  240.21  7357458555  26846147251
1  Jul 13, 2020  242.18  244.31  238.23  239.60  7787751468  26775071858
2  Jul 12, 2020  239.46  243.31  237.77  242.13  6596394718  27054158346
3  Jul 11, 2020  241.04  241.53  238.33  239.46  5643067316  26752161985
4  Jul 10, 2020  242.87  242.88  236.73  240.98  7281370522  26919422187

In [5]:
data_covid=pd.read_csv("dataset covid")
data_covid.head(10)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,14/07/2020,14,7,2020,4,2,Afghanistan,AF,AFG,38041757.0,Asia,8.456497
1,13/07/2020,13,7,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,9.158357
2,12/07/2020,12,7,2020,85,16,Afghanistan,AF,AFG,38041757.0,Asia,10.081028
3,11/07/2020,11,7,2020,458,37,Afghanistan,AF,AFG,38041757.0,Asia,10.291323
4,10/07/2020,10,7,2020,255,20,Afghanistan,AF,AFG,38041757.0,Asia,9.812901
5,09/07/2020,9,7,2020,59,1,Afghanistan,AF,AFG,38041757.0,Asia,10.351783
6,08/07/2020,8,7,2020,210,16,Afghanistan,AF,AFG,38041757.0,Asia,10.811803
7,07/07/2020,7,7,2020,433,56,Afghanistan,AF,AFG,38041757.0,Asia,11.148276
8,06/07/2020,6,7,2020,279,38,Afghanistan,AF,AFG,38041757.0,Asia,10.824947
9,05/07/2020,5,7,2020,348,7,Afghanistan,AF,AFG,38041757.0,Asia,11.166677